title: User Manual
lang: en
description: Turtlebot4 User Manual
repository: roni-kreinin/turtlebot4-user-manual

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

include:
  - _includes

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-tabs
