title: Automotive Electronics
lang: en
description: automotive-electronics
repository: scotthadzik/automotive-electronics
baseurl: /automotive-electronics

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

include:
  - _includes

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-tabs
