title: Run Docs Template
lang: en
description: RunDocsTemplate
repository: scotthadzik/RunDocsTemplate
baseurl: /RunDocsTemplate

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

include:
  - _includes

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-tabs
